### ISSUE TITLE
Error in parameter yaml is very hard to track down

### ISSUE THREAD

**Issue by andrewjhumphrey** [envato/stack_master#130]
I had an error in a parameter YAML file:
```
ami:
  latest_ami:
    owners: <SNIP>
      filters:
        name: not-for-public-consumption-*
```
Note the extra spaces in front of the filters element.

The error that stack_master produces does not reference the file that cause it at all, making it somewhat of a pain to track down.

```
 sm apply us-west-2 not-for-public-consumption --trace
Executing apply on not-for-public-consumption  in us-west-2
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/2.2.0/psych.rb:370:in `parse': (<unknown>): mapping values are not allowed in this context at line 4 column 13 (Psych::SyntaxError)
	from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
	from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/2.2.0/psych.rb:318:in `parse'
	from /usr/local/var/rbenv/versions/2.2.4/lib/ruby/2.2.0/psych.rb:245:in `load'
```

Would be nice if there was something in the trace that told you the file that went boom, to avoid having to manually call `YAML.load_file` on each yaml file in turn to find the culprit.

**Comment by simpsora** [comment]
I'm also running intot he same problem.  Passing `--debug` does not show the parameter files which are being loaded.

**Comment by rbayerl** [comment]
We run a `style` test suite that consists of `rubocop` (for Sparkleformation templates), `flake8` (for Lambda code), and (yamllint)[https://github.com/adrienverge/yamllint] (for `stack_master` configuration and parameter files). Perhaps incorporating something similar in your workflow or CI would be more useful than adding a YAML linter to `stack_master`.
