### ISSUE TITLE
Missing required parameter params[:role_arn]

### ISSUE THREAD

**Issue by gservat** [envato/stack_master#152]
I've just started looking at stack_master and I am stuck on this error message:

```
bundle exec stack_master status                                                                 │}
Fetching stack information: |=========================================================================================|│
error: missing required parameter params[:role_arn]. Use --trace to view backtrace
```

I'm running this from the basic `bundle exec stack_master init <region> <stack name>` command so I haven't made any further changes. Also, my `~/.aws/credentials` file has a bunch of different credentials set-up with a `[default]` one, which is the one it should be using.

Any ideas?

**Comment by patrobinson** [comment]
Can you run it again with the `--trace` argument and paste the output?

**Comment by gservat** [comment]
```
bundle exec stack_master apply --trace
Executing apply on test in ap-southeast-2
/Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/param_validator.rb:28:in `validate!': missing required parameter params[:role_arn] (ArgumentError)
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/param_validator.rb:13:in `validate!'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/plugins/response_target.rb:21:in `call'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/request.rb:70:in `send_request'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/assume_role_credentials.rb:49:in `refresh'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/refreshing_credentials.rb:20:in `initialize'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/assume_role_credentials.rb:40:in `initialize'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/shared_config.rb:148:in `new'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/shared_config.rb:148:in `assume_role_from_profile'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/shared_config.rb:109:in `assume_role_credentials_from_config'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/credential_provider_chain.rb:94:in `assume_role_with_profile'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/credential_provider_chain.rb:77:in `assume_role_credentials'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/credential_provider_chain.rb:12:in `block in resolve'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/credential_provider_chain.rb:11:in `each'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/credential_provider_chain.rb:11:in `resolve'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/aws-sdk-core/plugins/request_signer.rb:37:in `block in <class:RequestSigner>'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/configuration.rb:70:in `call'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/configuration.rb:70:in `call'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/configuration.rb:205:in `block in resolve_defaults'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/configuration.rb:57:in `each'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/configuration.rb:57:in `each'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/configuration.rb:204:in `resolve_defaults'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/configuration.rb:200:in `value_at'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/configuration.rb:189:in `block in resolve'
        from /Users/gonzalo.servat/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/set.rb:283:in `each_key'
        from /Users/gonzalo.servat/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/set.rb:283:in `each'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/configuration.rb:189:in `resolve'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/configuration.rb:177:in `apply_defaults'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/configuration.rb:150:in `build!'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/base.rb:68:in `build_config'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/base.rb:19:in `initialize'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/aws-sdk-core-2.6.43/lib/seahorse/client/base.rb:105:in `new'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/aws_driver/cloud_formation.rb:34:in `cf'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/aws_driver/cloud_formation.rb:27:in `block in describe_stacks'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/aws_driver/cloud_formation.rb:41:in `retry_with_backoff'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/aws_driver/cloud_formation.rb:26:in `describe_stacks'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/stack.rb:37:in `find'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/commands/apply.rb:37:in `stack'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/commands/apply.rb:53:in `diff_stacks'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/commands/apply.rb:19:in `perform'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/command.rb:23:in `block in perform'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/command.rb:22:in `catch'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/command.rb:22:in `perform'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/command.rb:11:in `block in perform'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/command.rb:10:in `tap'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/command.rb:10:in `perform'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/cli.rb:200:in `block (2 levels) in execute_stacks_command'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/cli.rb:197:in `each'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/cli.rb:197:in `block in execute_stacks_command'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/cli.rb:187:in `each'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/cli.rb:187:in `each_slice'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/cli.rb:187:in `execute_stacks_command'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/cli.rb:47:in `block (2 levels) in execute!'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/lib/stack_master/cli.rb:172:in `execute!'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/gems/stack_master-0.12.0/bin/stack_master:13:in `<top (required)>'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/bin/stack_master:23:in `load'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/bin/stack_master:23:in `<main>'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/gonzalo.servat/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by patrobinson** [comment]
This looks like a bug in the aws-sdk to me, we don't require you to set a `role_arn`.

I suspect there's something wrong with your credentials and this is just throwing an obscure error message

**Comment by gservat** [comment]
Yep, you're absolutely right. I had a `source_profile = default` in the `[default]` section and as soon as I removed that, I could run stack_master commands successfully.

Thanks @patrobinson !
