### ISSUE TITLE
Exception stacks are printed out as ruby arrays

### ISSUE THREAD

**Issue by viraptor** [envato/stack_master#260]
When something fails, stack_master prints out the exception type/message and an array with frames, which is not readable.
Instead of
```
[..., "/opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/stack_master-1.11.1/lib/stack_master/cli.rb:195:in `execute!'", "/opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/stack_master-1.11.1/bin/stack_master:13:in `<top (required)>'", "/opt/boxen/rbenv/versions/2.3.3/bin/stack_master:22:in `load'", "/opt/boxen/rbenv/versions/2.3.3/bin/stack_master:22:in `<main>'"]
```
This could be formatted as:
```
Stacktrace:
  ...
  /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/stack_master-1.11.1/lib/stack_master/cli.rb:195:in `execute!' 
  /opt/boxen/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/stack_master-1.11.1/bin/stack_master:13:in `<top (required)>'
  /opt/boxen/rbenv/versions/2.3.3/bin/stack_master:22:in `load' 
  /opt/boxen/rbenv/versions/2.3.3/bin/stack_master:22:in `<main>'
```

**Comment by patrobinson** [comment]
PRs welcome :trollface:
