### ISSUE TITLE
Issues on MRI 2.3

### ISSUE THREAD

**Issue by jacobbednarz** [envato/stack_master#84]
Whilst running on MRI 2.3, I've hit the following slew of errors.

```
$ bundle exec stack_master status

(eval):90: warning: constant ::TimeoutError is deprecated                                                                                                                           |
(eval):90: warning: constant ::TimeoutError is deprecated
Thread.exclusive is deprecated, use Mutex
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bogo-0.1.32/lib/bogo/memoization.rb:51:in `memoize'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/resources/aws.rb:19:in `load!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:556:in `block in compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bogo-0.1.32/lib/bogo/memoization.rb:60:in `memoize'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:545:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:105:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/template_compiler.rb:9:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/stack.rb:70:in `generate'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:45:in `get_status'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:15:in `block in perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:14:in `map'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:14:in `perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `block in perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `tap'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/cli.rb:137:in `block (2 levels) in execute!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/command.rb:178:in `call'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/command.rb:153:in `run'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/runner.rb:428:in `run_active_command'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/runner.rb:71:in `run!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/delegates.rb:15:in `run!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/cli.rb:166:in `execute!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/bin/stack_master:13:in `<top (required)>'
/opt/boxen/rbenv/versions/2.3.0/bin/stack_master:23:in `load'
/opt/boxen/rbenv/versions/2.3.0/bin/stack_master:23:in `<main>'
(eval):90: warning: constant ::TimeoutError is deprecated=========                                                                                                                  |
(eval):90: warning: constant ::TimeoutError is deprecated
Thread.exclusive is deprecated, use Mutex
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bogo-0.1.32/lib/bogo/memoization.rb:51:in `memoize'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/resources/aws.rb:19:in `load!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:556:in `block in compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bogo-0.1.32/lib/bogo/memoization.rb:60:in `memoize'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:545:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:105:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/template_compiler.rb:9:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/stack.rb:70:in `generate'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:45:in `get_status'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:15:in `block in perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:14:in `map'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:14:in `perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `block in perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `tap'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/cli.rb:137:in `block (2 levels) in execute!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/command.rb:178:in `call'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/command.rb:153:in `run'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/runner.rb:428:in `run_active_command'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/runner.rb:71:in `run!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/delegates.rb:15:in `run!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/cli.rb:166:in `execute!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/bin/stack_master:13:in `<top (required)>'
/opt/boxen/rbenv/versions/2.3.0/bin/stack_master:23:in `load'
/opt/boxen/rbenv/versions/2.3.0/bin/stack_master:23:in `<main>'
(eval):90: warning: constant ::TimeoutError is deprecated===========================                                                                                                |
(eval):90: warning: constant ::TimeoutError is deprecated
Thread.exclusive is deprecated, use Mutex
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bogo-0.1.32/lib/bogo/memoization.rb:51:in `memoize'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/resources/aws.rb:19:in `load!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:556:in `block in compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bogo-0.1.32/lib/bogo/memoization.rb:60:in `memoize'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:545:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:105:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/template_compiler.rb:9:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/stack.rb:70:in `generate'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:45:in `get_status'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:15:in `block in perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:14:in `map'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:14:in `perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `block in perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `tap'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/cli.rb:137:in `block (2 levels) in execute!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/command.rb:178:in `call'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/command.rb:153:in `run'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/runner.rb:428:in `run_active_command'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/runner.rb:71:in `run!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/delegates.rb:15:in `run!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/cli.rb:166:in `execute!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/bin/stack_master:13:in `<top (required)>'
/opt/boxen/rbenv/versions/2.3.0/bin/stack_master:23:in `load'
/opt/boxen/rbenv/versions/2.3.0/bin/stack_master:23:in `<main>'
(eval):90: warning: constant ::TimeoutError is deprecated===============================================                                                                            |
(eval):90: warning: constant ::TimeoutError is deprecated
Thread.exclusive is deprecated, use Mutex
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bogo-0.1.32/lib/bogo/memoization.rb:51:in `memoize'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/resources/aws.rb:19:in `load!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:556:in `block in compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bogo-0.1.32/lib/bogo/memoization.rb:60:in `memoize'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:545:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:105:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/template_compiler.rb:9:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/stack.rb:70:in `generate'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:45:in `get_status'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:15:in `block in perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:14:in `map'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:14:in `perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `block in perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `tap'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/cli.rb:137:in `block (2 levels) in execute!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/command.rb:178:in `call'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/command.rb:153:in `run'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/runner.rb:428:in `run_active_command'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/runner.rb:71:in `run!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/delegates.rb:15:in `run!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/cli.rb:166:in `execute!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/bin/stack_master:13:in `<top (required)>'
/opt/boxen/rbenv/versions/2.3.0/bin/stack_master:23:in `load'
/opt/boxen/rbenv/versions/2.3.0/bin/stack_master:23:in `<main>'
(eval):90: warning: constant ::TimeoutError is deprecated=================================================================                                                          |
(eval):90: warning: constant ::TimeoutError is deprecated
Thread.exclusive is deprecated, use Mutex
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bogo-0.1.32/lib/bogo/memoization.rb:51:in `memoize'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/resources/aws.rb:19:in `load!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:556:in `block in compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bogo-0.1.32/lib/bogo/memoization.rb:60:in `memoize'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:545:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:105:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/template_compiler.rb:9:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/stack.rb:70:in `generate'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:45:in `get_status'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:15:in `block in perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:14:in `map'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:14:in `perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `block in perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `tap'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/cli.rb:137:in `block (2 levels) in execute!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/command.rb:178:in `call'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/command.rb:153:in `run'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/runner.rb:428:in `run_active_command'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/runner.rb:71:in `run!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/delegates.rb:15:in `run!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/cli.rb:166:in `execute!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/bin/stack_master:13:in `<top (required)>'
/opt/boxen/rbenv/versions/2.3.0/bin/stack_master:23:in `load'
/opt/boxen/rbenv/versions/2.3.0/bin/stack_master:23:in `<main>'
(eval):90: warning: constant ::TimeoutError is deprecated=====================================================================================                                      |
(eval):90: warning: constant ::TimeoutError is deprecated
Thread.exclusive is deprecated, use Mutex
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bogo-0.1.32/lib/bogo/memoization.rb:51:in `memoize'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/resources/aws.rb:19:in `load!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:556:in `block in compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bogo-0.1.32/lib/bogo/memoization.rb:60:in `memoize'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:545:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:105:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/template_compiler.rb:9:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/stack.rb:70:in `generate'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:45:in `get_status'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:15:in `block in perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:14:in `map'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:14:in `perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `block in perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `tap'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/cli.rb:137:in `block (2 levels) in execute!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/command.rb:178:in `call'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/command.rb:153:in `run'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/runner.rb:428:in `run_active_command'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/runner.rb:71:in `run!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/delegates.rb:15:in `run!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/cli.rb:166:in `execute!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/bin/stack_master:13:in `<top (required)>'
/opt/boxen/rbenv/versions/2.3.0/bin/stack_master:23:in `load'
/opt/boxen/rbenv/versions/2.3.0/bin/stack_master:23:in `<main>'
(eval):90: warning: constant ::TimeoutError is deprecated=======================================================================================================                    |
(eval):90: warning: constant ::TimeoutError is deprecated
Thread.exclusive is deprecated, use Mutex
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bogo-0.1.32/lib/bogo/memoization.rb:51:in `memoize'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/resources/aws.rb:19:in `load!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:556:in `block in compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bogo-0.1.32/lib/bogo/memoization.rb:60:in `memoize'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:545:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sparkle_formation-1.2.0/lib/sparkle_formation/sparkle_formation.rb:105:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/template_compiler.rb:9:in `compile'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/stack.rb:70:in `generate'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:45:in `get_status'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:15:in `block in perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:14:in `map'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/commands/status.rb:14:in `perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `block in perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `tap'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/command.rb:9:in `perform'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/cli.rb:137:in `block (2 levels) in execute!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/command.rb:178:in `call'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/command.rb:153:in `run'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/runner.rb:428:in `run_active_command'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/runner.rb:71:in `run!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.8/lib/commander/delegates.rb:15:in `run!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/lib/stack_master/cli.rb:166:in `execute!'
/opt/boxen/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/stack_master-0.1.0/bin/stack_master:13:in `<top (required)>'
/opt/boxen/rbenv/versions/2.3.0/bin/stack_master:23:in `load'
/opt/boxen/rbenv/versions/2.3.0/bin/stack_master:23:in `<main>'
Fetching stack information: |=======================================================================================================================================================|
REGION         | STACK_NAME                  | STACK_STATUS    | DIFFERENT
---------------|-----------------------------|-----------------|----------
ap-southeast-2 | example-stack               |                 | Yes
```

Haven't dived into the cause (yet) but will post some more information once investigated.

**Comment by stevehodgkiss** [comment]
A new version of bogo was released. This issue is resolved for me. Feel free to re-open if this is still an issue for you.
